# Generated by Django 4.2.7 on 2023-12-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meseros', '0002_meseros_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meseros',
            name='Nacionalidad',
        ),
        migrations.AddField(
            model_name='meseros',
            name='nacionalidad',
            field=models.CharField(default='', max_length=27),
        ),
    ]
