# Generated by Django 4.2.7 on 2023-12-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='procedencia',
            field=models.CharField(default='', max_length=25),
        ),
    ]
