# Generated by Django 4.2.7 on 2023-12-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientes_procedencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
